version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: jpa_pg
    environment:
      POSTGRES_USER: moreira
      POSTGRES_PASSWORD: moreira
      POSTGRES_DB: jpa_db
    ports:
      - "5432:5432"
